In [1]:
pip install pandas


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
import numpy as np

In [4]:
s = pd.Series([10,20,30,40,50])
print(s)


0    10
1    20
2    30
3    40
4    50
dtype: int64


In [5]:
# Criando duas Series Pandas
#  .Series - tranforma os dados em colunas, mostrando o idex e o tipo do dado
s1 = pd.Series([10,20,30,40,50])
s2 = pd.Series([1,2,3,4,5])

In [6]:
# Soma
soma = s1 + s2
print("Soma:")
print(soma)

Soma:
0    11
1    22
2    33
3    44
4    55
dtype: int64


In [7]:
# Subtração
subtracao= s1 -s2
# \n - pular linha
print("\nSubtração:")
print(subtracao)


Subtração:
0     9
1    18
2    27
3    36
4    45
dtype: int64


In [8]:
# Multiplicação
multiplicacao= s1 * s2
print("\nMultiplicação:")
print(multiplicacao)


Multiplicação:
0     10
1     40
2     90
3    160
4    250
dtype: int64


In [9]:
# Divisão
divisao= s1 / s2
print("\nDivisão:")
print(divisao)


Divisão:
0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
dtype: float64


In [10]:
s1 = pd.Series([10,20,30,40,50],name='Série 1')
s2 = pd.Series([1,2,3,4,5],name='Série 2')

# Criando um DataFramea partir das Series
df= pd.DataFrame({'Série 1':s1,'Série 2':s2})
print(df)



   Série 1  Série 2
0       10        1
1       20        2
2       30        3
3       40        4
4       50        5


In [11]:
arr= np.array([[1,2,3],[4,5,6]])
result= arr * 2
print("ArrayNumPyoriginal:", arr)
print("\nArrayNumPyapós multiplicação por 2:", result)

ArrayNumPyoriginal: [[1 2 3]
 [4 5 6]]

ArrayNumPyapós multiplicação por 2: [[ 2  4  6]
 [ 8 10 12]]


In [12]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data)
df['C'] = df['A'] + df['B']
print("DataFrame Pandas:")
print(df)


DataFrame Pandas:
   A  B  C
0  1  4  5
1  2  5  7
2  3  6  9


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
element = arr[0, 2] 
print("Elemento acessado com NumPy:", element)

Elemento acessado com NumPy: 3


In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
element = arr[0, 2] 
print("Elemento acessado com NumPy:", element)

Elemento acessado com NumPy: 3


In [15]:
arr = np.array([1, 2, 3, 4, 5])
# Álgebra linear com NumPy
matriz = np.array([[1, 2], [3, 4]])
vetor = np.array([5, 6])
# Produto escalar
produto_escalar = np.dot(matriz, vetor)
# Estatísticas com NumPy
media = np.mean(arr)
desvio_padrao = np.std(arr)
print("Produto escalar com NumPy:", produto_escalar)
print("Média:", media)
print("Desvio padrão:", desvio_padrao)


Produto escalar com NumPy: [17 39]
Média: 3.0
Desvio padrão: 1.4142135623730951


In [16]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data)
df['C'] = df['A'] + df['B'] 
media_coluna_A = df['A'].mean()
soma_coluna_B = df['B'].sum()
print("DataFrame Pandas:")
print(df)
print("Média da coluna 'A':", media_coluna_A)
print("Soma da coluna 'B':", soma_coluna_B)

DataFrame Pandas:
   A  B  C
0  1  4  5
1  2  5  7
2  3  6  9
Média da coluna 'A': 2.0
Soma da coluna 'B': 15


In [20]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
# Gerando dados aleatórios com NumPy
np.random.seed(0)
data = np.random.normal(loc=0, scale=1, size=1000)
# Calculando estatísticas com SciPy
mean = np.mean(data)
std_dev = np.std(data)
# Visualizando os dados com Matplotlib
plt.hist(data, bins=30, density=True, alpha=0.5, color='blue')
xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, 100)
p = stats.norm.pdf(x, mean, std_dev)
plt.plot(x, p, 'k', linewidth=2)
plt.title('Distribuição Normal')
plt.show()


ModuleNotFoundError: No module named 'scipy'

In [17]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]}
df = pd.DataFrame(data)
print("Pandas DataFrame:")
print(df)



Pandas DataFrame:
   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("NumPy ndarray:")
print(arr)

NumPy ndarray:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("NumPy ndarray (tridimensional):")
print(arr)


NumPy ndarray (tridimensional):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
